builds:
  - ldflags:
      - -s -w -X github.com/scottmcclary1/predix-insights-cli/cmd.Version={{.Tag}} -X github.com/scottmcclary1/predix-insights-cli/cmd.GitHash={{.Commit}}
    main: main.go
    binary: pi
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
brew:
  github:
    owner: scottmcclary1
    name: homebrew-tap
  folder: Formula
  caveats: "source ~/.bashrc"
  homepage:  https://www.predix.io/
  description: PI is a CLI library for Predix Insights. This top technology lets you concentrate on building analytical pipelines, not managing infrastructure.
  dependencies:
    - bash-completion
  test: |
    system "#{bin}/pi --version"
  install: |
    bin.install "pi"
    mkdir_p "#{HOMEBREW_PREFIX}/etc/bash_completion.d"
    cp "scripts/pi_completion.sh", "#{HOMEBREW_PREFIX}/etc/bash_completion.d"
    system "echo 'if [ -f $(brew --prefix)/etc/bash_completion ]; then . $(brew --prefix)/etc/bash_completion; fi' >> ~/.bashrc"
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - scripts/pi_completion.sh
