builds:
  - ldflags:
      - -s -w -X github.com/scottmcclary1/predix-insights-cli/cmd.Version={{.Tag}} -X github.com/scottmcclary1/predix-insights-cli/cmd.GitHash={{.Commit}}
    main: main.go
    binary: pi
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
brew:
  github:
    owner: scottmcclary1
    name: homebrew-tap
  folder: Formula
  homepage:  https://www.predix.io/
  description: PI is a CLI library for Predix Insights. This top technology lets you concentrate on building analytical pipelines, not managing infrastructure.
  test: |
    system "#{bin}/pi --version"
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
