builds:
  - ldflags:
      - -s -w -X github.com/scottmcclary1/predix-insights-cli/cmd.Version={{.Tag}} -X github.com/scottmcclary1/predix-insights-cli/cmd.GitHash={{.Commit}} -X github.com/scottmcclary1/predix-insights-cli/cmd.GitDate={{.Date}}
    main: main.go
    binary: pi
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
git:
  short_hash: true
brew:
  github:
    owner: scottmcclary1
    name: homebrew-tap
  folder: Formula
  caveats: "Run the following command or open a new terminal tab/window:\n  source ~/.bash_profile"
  homepage:  https://www.predix.io/
  description: PI is a CLI library for Predix Insights. This top technology lets you concentrate on building analytical pipelines, not managing infrastructure.
  dependencies:
    - bash-completion
  test: |
    system "#{bin}/pi --version"
  install: |
    bin.install "pi"
    mkdir_p "#{HOMEBREW_PREFIX}/etc/bash_completion.d"
    cp "scripts/pi_completion.sh", "#{HOMEBREW_PREFIX}/etc/bash_completion.d"
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - scripts/pi_completion.sh
