builds:
  - main: main.go
    flags:
      - -ldflags "-X github.com/scottmcclary1/predix-insights-cli/cmd.Version=`cat version` -X github.com/scottmcclary1/predix-insights-cli/cmd.GitHash=`git rev-parse HEAD`"
    binary: pi
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
