language: go
go:
  - "1.10"
install:
  - wget "https://github.com/Masterminds/glide/releases/download/0.13.1/glide-0.13.1-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-0.13.1-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"
  - glide install --strip-vendor
deploy:
- provider: script
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  script: curl -sL https://git.io/goreleaser | bash
  on:
    condition: $TRAVIS_OS_NAME = linux
    tags: true
